### ISSUE TITLE
fontawesome not rendering

### ISSUE THREAD

**Issue by shannonpileggi** [spcanelon/RLadies-xaringan-template#1]
Hi Silvia! I am trying to use this template to create some slides, and `fontawesome` isn't rendering correctly.  

The slides were generated from 

1. `usethis::use_course("spcanelon/RLadies-xaringan-template")`
2. knit `index.Rmd`

and here is what I am seeing:

![image](https://user-images.githubusercontent.com/17747575/113849963-fa32f000-9767-11eb-9021-3d1fb82ae5b4.png)

I did initially have some trouble with installing `fontawesome` and `htmltools`. I updated R to 4.0.5 and the installation issue resolved. In addition, I am working on Windows 10. Do you have any ideas to further troubleshoot? 

Below is my session info. I'm not too happy about that error on the 3rd line and I am wondering if I have some bigger installation issue as well.

``` r
library(fontawesome)
devtools::session_info()
#> Error in get(genname, envir = envir) : object 'testthat_print' not found
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.5 (2021-03-31)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2021-04-07                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  backports     1.1.7   2020-05-13 [1] CRAN (R 4.0.0)
#>  callr         3.4.4   2020-09-07 [1] CRAN (R 4.0.2)
#>  cli           2.3.1   2021-02-23 [1] CRAN (R 4.0.4)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools      2.3.2   2020-09-18 [1] CRAN (R 4.0.2)
#>  digest        0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
#>  ellipsis      0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
#>  fontawesome * 0.2.0   2021-03-28 [1] CRAN (R 4.0.4)
#>  fs            1.4.1   2020-04-04 [1] CRAN (R 4.0.0)
#>  glue          1.4.1   2020-05-13 [1] CRAN (R 4.0.0)
#>  highr         0.8     2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools     0.5.1.1 2021-01-22 [1] CRAN (R 4.0.4)
#>  knitr         1.31    2021-01-27 [1] CRAN (R 4.0.3)
#>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
#>  magrittr      2.0.1   2020-11-17 [1] CRAN (R 4.0.4)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
#>  pillar        1.5.1   2021-03-05 [1] CRAN (R 4.0.4)
#>  pkgbuild      1.1.0   2020-07-13 [1] CRAN (R 4.0.2)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  pkgload       1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
#>  processx      3.4.2   2020-02-09 [1] CRAN (R 4.0.0)
#>  ps            1.3.3   2020-05-08 [1] CRAN (R 4.0.0)
#>  purrr         0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
#>  remotes       2.2.0   2020-07-21 [1] CRAN (R 4.0.2)
#>  reprex        1.0.0   2021-01-27 [1] CRAN (R 4.0.3)
#>  rlang         0.4.10  2020-12-30 [1] CRAN (R 4.0.3)
#>  rmarkdown     2.6     2020-12-14 [1] CRAN (R 4.0.3)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
#>  rstudioapi    0.13    2020-11-12 [1] CRAN (R 4.0.4)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi       1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  styler        1.3.2   2020-02-23 [1] CRAN (R 4.0.3)
#>  testthat      2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
#>  tibble        3.1.0   2021-02-25 [1] CRAN (R 4.0.4)
#>  usethis       2.0.1   2021-02-10 [1] CRAN (R 4.0.3)
#>  utf8          1.1.4   2018-05-24 [1] CRAN (R 4.0.0)
#>  vctrs         0.3.4   2020-08-29 [1] CRAN (R 4.0.2)
#>  withr         2.4.1   2021-01-26 [1] CRAN (R 4.0.3)
#>  xfun          0.21    2021-02-10 [1] CRAN (R 4.0.3)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] C:/Users/Shannon.Pileggi/OneDrive - OneWorkplace/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.5/library
```

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by spcanelon** [comment]
Hey Shannon! 

I'm sorry the icons aren't rendering! What a bummer. I don't know enough about what's going on to have a solution for you but I *do* have a workaround!

You can also add Fontawesome icons to your slides using the `icons` package being developed in the [mitchelloharawild/icons](https://github.com/mitchelloharawild/icons#icons-) repo:

```
# install.packages("remotes")
remotes::install_github("mitchelloharawild/icons")
```

Here's [an example from another slide deck](https://github.com/spcanelon/xaringan-basics-and-beyond/blob/main/slides/day-01-basics.Rmd#L122-L124):

```rmd
[`r icons::fontawesome("link")` silvia.rbind.io](https://silvia.rbind.io)
[`r icons::fontawesome("twitter")` @spcanelon](https://twitter.com/spcanelon)
[`r icons::icon_style(icons::fontawesome("github"), scale = 1)` @spcanelon](https://github.com/spcanelon)
```

You'll notice the syntax is a little different. You have to wrap your call to `fontawesome()` within the `icon_style()` function if you want to style the icons (change the size with scale, change the fill color, etc). The package is currently undergoing some big development updates, so just know that features may change in the future and it may end up getting [moved back over to the rOpenScilabs repo](https://github.com/mitchelloharawild/icons#a-note-on-the-old-api).

Lastly, here are my thoughts about what might be going on:

What I see in your screenshot is the SVG code responsible for creating the icons. You would also see this code if you ran the same `fontawesome::fa()` function in your console, for example. This suggests to me that there's some error when it comes time to render the icons within the html slides but I'm not sure what could be causing it. 🤷🏽
You have the latest version of `fontawesome` so the only thing I can suggest is maybe installing the development version of `xaringan` (which I didn't see listed in your session info)?

```
remotes::install_github('yihui/xaringan')
```

**Comment by shannonpileggi** [comment]
Ay ay ay of course.  I was on {xaringan} 0.19. I updated to {xaringan} 0.20 on CRAN and that fixed it! 🤦 Sorry to take your time on this! And thank you for this wonderful starter!

**Comment by spcanelon** [comment]
Hey no worries at all, I'm glad you got it working! 🙂 

And it makes me happy to know that at least one person is using the template! 😅  Feedback is very welcome!
